### ISSUE TITLE
Spelling mistake in filter-map.js

### ISSUE THREAD

**Issue by dleeftink** [mathisonian/svg-filter#1]
Hi @mathisonian, I think `feDiffuseLightning` is supposed to map to `feDiffuseLighting` without an extra `n` before `-ing`.

**Comment by mathisonian** [comment]
Fixed in https://github.com/mathisonian/svg-filter/commit/829417ffe6167bb580bc0ef622f7e3e3f1c23f4b, thanks for flagging!
